### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by dog-broad** [fjme2/ShinyGo#4]
Hey, this project looks interesting could u possibly elobrate abt this?? Pls

**Comment by Fmaes2** [comment]
Hi! At first the idea of the proyect was to create a telegram bot to record the shiny Pokemon that you had caught in Pokemon Go. But at the end it was a proyect to know how many stardust do you need to level up a Pokemon in Pokemon Go.
All of this was before the big update of the levels and the proyect is not up to date with the game.

> 
> 
> Hey, this project looks interesting could u possibly elobrate abt this?? Pls

**Comment by dog-broad** [comment]
oh ok nice
lol
